---
html_document: null
output: null
resource_files:
- slowregard1chars.RDS
- slowregard1text.RDS
- SlowRegard1.hd5
runtime: shiny
self_contained: no
---

```{r echo=FALSE} 
library(knitr)
opts_chunk$set(echo=FALSE,message=FALSE,warning=FALSE,cache=FALSE)
```

```{r,message=FALSE}

library(ggplot2)
library(dplyr)
library(keras)
library(readr)
library(stringr)
library(purrr)
library(tokenizers)
```

```{R SHINYTRY, warning=FALSE}
model<- load_model_hdf5('EEmodel2.hd5')
text<- readRDS('EE2text.RDS')
chars<- readRDS('EE2chars.RDS')

```


```{r predict}
maxlen<-50

sample_mod <- function(preds, temperature = 1){
  preds <- log(preds)/temperature
  exp_preds <- exp(preds)
  preds <- exp_preds/sum(exp(preds))
  
  rmultinom(1, 1, preds) %>% 
    as.integer() %>%
    which.max()
}

nextindex<- function(sentence,diversity){
  x <- sapply(chars, function(x){
      as.integer(x == sentence)
    })
    x <- array_reshape(x, c(1, dim(x)))
    
    preds <- predict(model, x)
    next_index <- sample_mod(preds, diversity)
}


generateText<-function(chapter_length=10,sentence="",diversity=1){
  sentence<-paste(sentence,"\n\n",sep="")
  originalSentence<-paste(sentence,"\n\n",sep="")
  sentence<-strsplit(sentence,split=NULL)[[1]]
  sentence_length<- length(sentence)
  
  if (sentence_length>maxlen){
    sentence<-sentence[1:maxlen]
  }
  
  if (sentence_length<maxlen){
    missing<-maxlen-sentence_length
    start_index <- sample(1:(length(text) - maxlen), size = 1)
    ss <- text[start_index:(start_index + missing - 1)]
    sentence<-c(ss,sentence)
  }
  
  generated<-""
  
  for(i in 1:chapter_length){
    next_index<-nextindex(sentence,diversity)
    next_char <- chars[next_index]
    generated <- str_c(generated, next_char, collapse = "")
    sentence <- c(sentence[-1], next_char)
  }
  originalSentence<-str_c(originalSentence,collapse="")
  generated<- paste(originalSentence,generated,sep='')
}

```

```{r}


maketext <- reactive({
  input$update
  isolate({
    withProgress({
      setProgress(message = "Creating a new poem...")
      generateText(input$chapter_length,
                   sentence=input$seedwords,
                   diversity=input$creativity)
      })
  })
})


fluidPage(
  titlePanel('E. E. Essence'),
  
  sidebarLayout(
    sidebarPanel(
      numericInput(inputId = "chapter_length",label="Poem Length",
                   min=1,max=20000,value=500,step=100),
      textInput('seedwords',label='Optional: choose title of poem (30 chars max):',
                value='anyone lived in a pretty how town'),
      shinyjs::runjs("$('#seedwords').attr('maxlength', 30)"),
      sliderInput("creativity", "Creativity:",
                  min = 0.05, max = 3,
                  value = 0.5, step = 0.05),
      actionButton("update", "Write!"),
      p(),
      em('E. E. Cummings'),
      div('Was a poet with a distinct style that is immediately recognizable by anyone familiar with his work. We trained a neural network to abstract the essence of that style and to generate new, completely original poems. The true meaning of these new poems may be beyond our understanding as humans, but perhaps with deeper study these will help us understand the emotional side of artificial intelligence. '),
      p('If you wish, you may enter a title to inspire the new poem, or leave it up to the artificial poet.')
    ),
  mainPanel(
    tags$style(type="text/css", "#Output_text {white-space: pre-wrap;}"),
    textOutput("Output_text")
    )
  )
)

# output$writer<-renderText({gen$generated})

output$Output_text<-renderText(
  maketext()
)

```


<!-- https://github.com/keras-team/keras/blob/master/examples/lstm_text_generation.py -->

<!-- https://www.amazon.com/Regard-Silent-Things-Kingkiller-Chronicle/dp/0756411327 -->
