---
title: "R Notebook"
output: html_notebook
---



```{r echo=FALSE} 
library(knitr)
opts_chunk$set(echo=FALSE,message=FALSE,warning=FALSE,cache=FALSE)
```

```{r,message=FALSE,echo=FALSE}

library(ggplot2)
library(dplyr)
library(knitr)
library(tidyr)
library(broom)
# library(grid)
library(relaimpo)
library(leaps)
library(stringr)
library(cladoRcpp)
library(boot)
source('Adamhelperfunctions.R')
source('fixationanalysisfunctions.R')
select<- dplyr::select
```

```{r load,cache=FALSE}
#skip the next two chunks (quickload and mark saccades) if you load this.
 # t<- readRDS('INCsaccadesmarked.RDS')
 t<- readRDS('OMNstrabMeasured4-19-2018.RDS') 

```

```{r quickload,echo=FALSE,cache=TRUE}
LoadFromFile<- FALSE

if (LoadFromFile){
  o<- readRDS('OMNstrab.RDS')
}else{
  o<-NULL
}

t<- loadnewcsv2(path="C:/Users/setup/Desktop/NRTP Vergence/OMNfinal/",referencefile=o)


t<- rbind(o,t)

o<-NULL

```


```{r mark saccades,cache=FALSE,eval=FALSE}

t %>%
  group_by(neuron) %>%
  mutate(time=row_numer()) %>%
  do(measureSaccadesINC(.))-># %>%
  # do(expandSaccades(.,buffer=80))->
  t

# saveRDS(t,'OMNstrabMeasured4-19-2018.RDS')

```

```{r Measure_Fixations,warning=FALSE}


zp<-measureFixations(t)

maxEP<- 25
zp<- filter(zp,
            dur>200,
            abs(mean.R.H)<maxEP,
            abs(mean.L.H)<maxEP,
            abs(mean.R.V)<maxEP,
            abs(mean.L.V)<maxEP,
            meanFR<500)



```

```{r plotFunctions,echo=FALSE}

compare2cells<- function(zp,zmc,c1,c2,maxEP=25,color1='black',color2='black',
                         c1name=NA,c2name=NA){
  
  if(is.na(c1name)){c1name=c1}
  if(is.na(c2name)){c2name=c2}
  
zp<- filter(zp,
            neuron %in% c(c1,c2),
            dur>200,
            abs(mean.R.H)<maxEP,
            abs(mean.L.H)<maxEP,
            abs(mean.R.V)<maxEP,
            abs(mean.L.V)<maxEP,
            meanFR<500)
  
tab<-zmc %>%
  filter(neuron %in% c(c1,c2)) %>%
  select(neuron,R2,H.R2,V.R2,dir.pref.slope,dir.pref.imp)

nV<-ggplot(zp %>% filter(neuron==c1))+
  geom_point(aes(mean.V,meanFR),color=color1)+
  stat_smooth(aes(mean.V,meanFR),color='black',se=FALSE,method=lm)+
  xlab('')+
  theme_minimal()+
  ylab(paste(c1name,'\nMean Firing Rate (spk/s)'))

nH<-ggplot(zp %>% filter(neuron==c1))+
  geom_point(aes(mean.H,meanFR),color=color1)+
  stat_smooth(aes(mean.H,meanFR),color='black',se=FALSE,method=lm)+
  xlab('')+
  ylab('')+
  theme_minimal()

  sV<-ggplot(zp %>% filter(neuron==c2))+
    geom_point(aes(mean.V,meanFR),color=color2)+
    stat_smooth(aes(mean.V,meanFR),color='black',se=FALSE,method=lm)+
    xlab('Mean Vertical Eye Position (deg)')+
    ylab(paste(c2name,'\nMean Firing Rate (spk/s)'))+
    theme_minimal()
  
  sH<-ggplot(zp %>% filter(neuron==c2))+
    geom_point(aes(mean.H,meanFR),color=color2)+
    stat_smooth(aes(mean.H,meanFR),color='black',se=FALSE,method=lm)+
    xlab('Mean Horizontal Eye Position (deg)')+
    ylab('')+
    theme_minimal()


#make a named list to manually color the direction plots
color.values<-NULL
color.values[[c1]]<-color1
color.values[[c2]]<-color2

dir.imp<-ggplot(tab)+
  # geom_segment(aes(y=0,yend=1,x=dir.pref.imp,xend=dir.pref.imp),color='black')+
  geom_segment(aes(y=0,yend=1,x=dir.pref.imp,xend=dir.pref.imp,color=neuron))+
  scale_color_manual(values=color.values)+
  scale_x_continuous(limits=c(-180,180),breaks=c(0,90,180,-90))+
  coord_polar(start=pi/2,direction=-1)+
  theme_minimal()+
  theme(legend.position='none')+
  xlab('Direction preference\nusing relative importance')

dir.slope<-ggplot(tab)+
  geom_segment(aes(y=0,yend=1,x=dir.pref.slope,xend=dir.pref.slope,color=neuron))+
  scale_color_manual(values=color.values)+
  scale_x_continuous(limits=c(-180,180),breaks=c(0,90,180,-90))+
  coord_polar(start=pi/2,direction=-1)+
  theme_minimal()+
  theme(legend.position='none')+
  xlab('Direction Preference\nusing slopes')

# print(multiplot(nV,sV,dir.slope,nH,sH,dir.imp,cols=2))


return(list(nV,sV,dir.slope,nH,sH,dir.imp))


}

show1cell<- function(zp,zmc,c1,maxEP=25,color1='black',c1name=NA){
  
  if(is.na(c1name)){c1name=c1}

zp<- filter(zp,
            neuron == c1,
            dur>200,
            abs(mean.R.H)<maxEP,
            abs(mean.L.H)<maxEP,
            abs(mean.R.V)<maxEP,
            abs(mean.L.V)<maxEP,
            meanFR<500)
  
tab<-zmc %>%
  filter(neuron == c1) %>%
  select(neuron,R2,H.R2,V.R2,dir.pref.slope,dir.pref.imp)

nV<-ggplot(zp %>% filter(neuron==c1))+
  geom_point(aes(mean.V,meanFR),color=color1)+
  stat_smooth(aes(mean.V,meanFR),color='black',se=FALSE,method=lm)+
  xlab('Mean Horizontal Eye Position (deg)')+
  theme_minimal()+
  ylab(paste(c1name,'\nMean Firing Rate (spk/s)'))

nH<-ggplot(zp %>% filter(neuron==c1))+
  geom_point(aes(mean.H,meanFR),color=color1)+
  stat_smooth(aes(mean.H,meanFR),color='black',se=FALSE,method=lm)+
  xlab('Mean Vertical Eye Position (deg)')+
  ylab('')+
  theme_minimal()


#make a named list to manually color the direction plots
color.values<-NULL
color.values[[c1]]<-color1

dir.imp<-ggplot(tab)+
  # geom_segment(aes(y=0,yend=1,x=dir.pref.imp,xend=dir.pref.imp),color='black')+
  geom_segment(aes(y=0,yend=1,x=dir.pref.imp,xend=dir.pref.imp,color=neuron))+
  scale_color_manual(values=color.values)+
  scale_x_continuous(limits=c(-180,180),breaks=c(0,90,180,-90))+
  coord_polar(start=pi/2,direction=-1)+
  theme_minimal()+
  theme(legend.position='none')+
  xlab('Direction preference\nusing relative importance')

dir.slope<-ggplot(tab)+
  geom_segment(aes(y=0,yend=1,x=dir.pref.slope,xend=dir.pref.slope,color=neuron))+
  scale_color_manual(values=color.values)+
  scale_x_continuous(limits=c(-180,180),breaks=c(0,90,180,-90))+
  coord_polar(start=pi/2,direction=-1)+
  theme_minimal()+
  theme(legend.position='none')+
  xlab('Direction Preference\nusing slopes')

# print(multiplot(nV,sV,dir.slope,nH,sH,dir.imp,cols=2))


return(list(nV,dir.slope,nH,dir.imp))

}

```

```{r Fixation_Analysis,cache=FALSE,warning=FALSE}


zp %>%
    filter(meanFR>0,dur<1000,mean.conj.velocity<3) %>%
  group_by(neuron) %>%
  mutate(n=n()) %>%
  filter(n>20) %>%
  do(calculateDirPrefFixations(.)) %>%
  separate(neuron,c('monkey','cellnum'),remove=FALSE)->
  zm



```
#Results

```{r RegularCells,fig.height=7,fig.width=6}
Ncell<- 'Patos-107'
Scell<- 'Patos-110'



tab<-zmc %>%
  filter(neuron %in% c(Ncell,Scell)) %>%
  select(neuron,R2,H.R2,V.R2,dir.pref.slope,dir.pref.imp)

multiplot(plotlist=compare2cells(zp,zmc,Ncell,Scell,color1='purple',color2='orange',
                                 c1name=Ncell,c2name=Scell),cols=2)

kable(tab,digits=2)

```

\pagebreak

###Direction Preferences
Using RIGHT EYE only
```{r,fig.height=6}
multiplot(
ggplot(zm)+
  geom_segment(aes(y=0,yend=1,x=dir.imp.R,xend=dir.imp.R,color=monkey))+
  scale_x_continuous(limits=c(-180,180),breaks=c(0,90,180,-90))+
  coord_polar(start=pi/2,direction=-1)+
  theme_minimal()+
  theme(legend.position='none')+
  facet_wrap(~monkey,ncol=4)+
  xlab('')+
  ylab(''),
ggplot(zm)+
  geom_segment(aes(y=0,yend=R2R,x=dir.imp.R,xend=dir.imp.R,color=monkey))+
  scale_x_continuous(limits=c(-180,180),breaks=c(0,90,180,-90))+
  coord_polar(start=pi/2,direction=-1)+
  theme_minimal()+
  theme(legend.position='none')+
  facet_wrap(~monkey,ncol=4)+
  xlab('Direction preference\nusing relative importance')+
  ylab('R-squared'),
cols=1
)

```

```{r lefteye, fig.height=6}
multiplot(
ggplot(zm)+
  geom_segment(aes(y=0,yend=1,x=dir.imp.L,xend=dir.imp.L,color=monkey))+
  scale_x_continuous(limits=c(-180,180),breaks=c(0,90,180,-90))+
  coord_polar(start=pi/2,direction=-1)+
  theme_minimal()+
  theme(legend.position='none')+
  facet_wrap(~monkey,ncol=4)+
  xlab('')+
  ylab(''),
ggplot(zm)+
  geom_segment(aes(y=0,yend=R2L,x=dir.imp.L,xend=dir.imp.L,color=monkey))+
  scale_x_continuous(limits=c(-180,180),breaks=c(0,90,180,-90))+
  coord_polar(start=pi/2,direction=-1)+
  theme_minimal()+
  theme(legend.position='none')+
  facet_wrap(~monkey,ncol=4)+
  xlab('Direction preference\nusing relative importance')+
  ylab('R-squared'),
cols=1
)

```


CONJUGATE
```{r conjugate, fig.height=6}
multiplot(
ggplot(zm)+
  geom_segment(aes(y=0,yend=1,x=dir.pref.imp, xend=dir.pref.imp,color=monkey))+
  scale_x_continuous(limits=c(-180,180),breaks=c(0,90,180,-90))+
  coord_polar(start=pi/2,direction=-1)+
  theme_minimal()+
  theme(legend.position='none')+
  facet_wrap(~monkey,ncol=4)+
  xlab('')+
  ylab(''),
ggplot(zm)+
  geom_segment(aes(y=0,yend=R2,x=dir.pref.imp,xend=dir.pref.imp,color=monkey))+
  scale_x_continuous(limits=c(-180,180),breaks=c(0,90,180,-90))+
  coord_polar(start=pi/2,direction=-1)+
  theme_minimal()+
  theme(legend.position='none')+
  facet_wrap(~monkey,ncol=4)+
  xlab('Direction preference\nusing relative importance')+
  ylab('R-squared'),
cols=1
)

```