---
html_document: null
output: null
resource_files:
- slowregard1chars.RDS
- slowregard1text.RDS
- SlowRegard1.hd5
runtime: shiny
self_contained: no
---


```{r echo=FALSE} 
library(knitr)
opts_chunk$set(echo=FALSE)
```

```{r,message=FALSE}

library(ggplot2)
library(dplyr)
library(keras)
library(readr)
library(stringr)
library(purrr)
library(tokenizers)

#library(knitr)
#library(tidyr)
#library(broom)
#library(grid)
# library(relaimpo)
# library(leaps)
#library(data.table)

```


```{R SHINYTRY, warning=FALSE}
# model<- load_model_hdf5('C:/Users/setup/Dropbox/deeplearning/slowregard1/SlowRegard1.hd5')
# text<- readRDS('C:/Users/setup/Dropbox/deeplearning/slowregard1/slowregard1text.RDS')
# chars<- readRDS('C:/Users/setup/Dropbox/deeplearning/slowregard1/slowregard1chars.RDS')

model<- load_model_hdf5('SlowRegard1.hd5')
text<- readRDS('slowregard1text.RDS')
chars<- readRDS('slowregard1chars.RDS')

# model<- load_model_hdf5('SlowRegard8.hd5')
# text<- readRDS('slowregard8text.RDS')
# chars<- readRDS('slowregard8chars.RDS')


```


```{r predict}
maxlen<-30
sample_mod <- function(preds, temperature = 1){
  preds <- log(preds)/temperature
  exp_preds <- exp(preds)
  preds <- exp_preds/sum(exp(preds))
  
  rmultinom(1, 1, preds) %>% 
    as.integer() %>%
    which.max()
}
# 
# diversity=1
# 
# # poem_length=as.integer(runif(n=1,min=200,max=2000))
# poem_length=2000
# # for(diversity in c(0.80)){  
# 
# 
# start_index <- sample(1:(length(text) - maxlen), size = 1)
# sentence <- text[start_index:(start_index + maxlen - 1)]
# generated <- ""


# diversity=1

# for(i in 1:poem_length){
#   
#   x <- sapply(chars, function(x){
#     as.integer(x == sentence)
#   })
#   x <- array_reshape(x, c(1, dim(x)))
#   
#   preds <- predict(model, x)
#   next_index <- sample_mod(preds, diversity)
#   next_char <- chars[next_index]
#   
#   generated <- str_c(generated, next_char, collapse = "")
#   sentence <- c(sentence[-1], next_char)
#   
# }


generateText<-function(model,chapter_length,text,chars,sentence,diversity){
  diversity=1
  originalSentence<-sentence
  sentence<-strsplit(sentence,split=NULL)[[1]]
  sentence_length<- length(sentence)
  
  if (sentence_length>maxlen){
    # message('too big')
    sentence<-sentence[1:maxlength]
  }
  
  if (sentence_length<maxlen){
    # message('too small')
    missing<-maxlen-sentence_length
    start_index <- sample(1:(length(text) - maxlen), size = 1)
    ss <- text[start_index:(start_index + missing - 1)]
    sentence<-c(ss,sentence)
  }
  generated<-""
  for(i in 1:chapter_length){
    
    x <- sapply(chars, function(x){
      as.integer(x == sentence)
    })
    x <- array_reshape(x, c(1, dim(x)))
    
    preds <- predict(model, x)
    next_index <- sample_mod(preds, diversity)
    next_char <- chars[next_index]
    
    generated <- str_c(generated, next_char, collapse = "")
    sentence <- c(sentence[-1], next_char)
    
  }
  originalSentence<-str_c(originalSentence,collapse="")
  generated<- paste(originalSentence,generated,sep='')
  generated<-str_replace_all(generated,'\n\n','\n')
}

```

```{r}

maketext <- reactive({
  input$update
  isolate({
    withProgress({
      setProgress(message = "Writing a new chapter...")
      generateText(model,input$chapter_length,text,chars,
                   sentence=input$seedwords,
                   diversity=input$creativity)
    })
  })
})

fluidPage(
  titlePanel('Slow Regard of Deep Learning'),
  
  sidebarLayout(
    sidebarPanel(
      numericInput(inputId = "chapter_length",label="Chapter Length",
                   min=200,max=20000,value=2000,step=100),
      textInput('seedwords',label='Enter a sentence (30 chars max)',
                value='Just then Auri opened her eyes'),
      shinyjs::runjs("$('#seedwords').attr('maxlength', 30)"),
      sliderInput("creativity", "Creativity:",
                  min = 0.1, max = 2,
                  value = 1, step = 0.1),
      actionButton("update", "Write!"),
      p(),
      em('The Slow Regard of Silent Things'),
      div('is a novella by Patrick Rothfuss about a week in the life of a mysterious character known as Auri, originally introduced in '),
      em('The Name Of the Wind'),
      div('book one of the Kingkiller Chronicle.'),
      p('We used keras for R to train a deep learning model to produce text in the style of this book. Each new chapter is totally unique, written character-by-character which means it often creates new words just as Rothfuss did in the original work.'),
      p('If you wish, you may write the first sentence.')
    ),
  mainPanel(
    tags$style(type="text/css", "#Output_text {white-space: pre-wrap;}"),
    textOutput("Output_text"))
  )
)


output$Output_text<-renderText(
  maketext()
  # generateText(model,input$chapter_length,text,chars)
# })
)



```


<!-- https://github.com/keras-team/keras/blob/master/examples/lstm_text_generation.py -->

<!-- https://www.amazon.com/Regard-Silent-Things-Kingkiller-Chronicle/dp/0756411327 -->
